### ISSUE TITLE
Show cluster summary of available node resources

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/dashboard#7109]
### What would you like to be added?

I would like the node resources to be aggregated in the "Cluster" view, the same way that pods are in the "Workload" view.

This would show a summary of _all_ the nodes, with their status and their cpu/memory/pods allocation.

Here is a screenshot from my implementation, using pie charts (different colors for requests and for limits):

![kubernetes-cluster-status](https://user-images.githubusercontent.com/10364051/168869140-41fce245-8db2-4412-bd9b-d482181008c9.png)

### Why is this needed?

Currently there is a list of nodes, and a detail page of each. But there is no cluster summary.

The other pages are also missing the capacity information, but that will be a separate issue.

![node-capacity](https://user-images.githubusercontent.com/10364051/168897501-219a769f-09cb-45b7-9b49-b00e639b3b6f.png)

**Comment by afbjorklund** [comment]
Possibly same feature as:
* #5657

**Comment by maciaszczykm** [comment]
Reopening as https://github.com/kubernetes/dashboard/pull/7110 was reverted in https://github.com/kubernetes/dashboard/pull/7358.

**Comment by afbjorklund** [comment]
Reason for reverting was here: https://github.com/kubernetes/dashboard/pull/7110#pullrequestreview-1071013359

It wanted nodes to be handled differently from pods.

> You can create cumulative statuses in the frontend code

**Comment by afbjorklund** [comment]
@maciaszczykm : I don't really understand how this would work...

I can only find the fields on NodeDetail, but not on Node(List) ?

`Property 'allocatedResources' does not exist on type 'Node'.`

**Comment by afbjorklund** [comment]
The way I understood it, only a partial set of the nodes is sent - and then paged through with the controls...

```
Incoming HTTP/1.1 GET /api/v1/node?itemsPerPage=10&page=1&sortBy=d,creationTimestamp request
```

This makes it unsuitable to aggregate resources over the entire cluster, which was why that data was added.

----

It works if **only** wanting to show the status (in Cluster Status), the way it is currently done in Workload Status.

But not for the additional feature of also showing cpu/memory/pod resources, since that needs more data (Status).

![Screenshot from 2022-08-15 08-11-18](https://user-images.githubusercontent.com/10364051/184585204-a63505ca-22b1-4027-97ed-ca36629e06b8.png)

**Comment by afbjorklund** [comment]
If anything, I would like to add _more_ Cluster data in the future. Such as the current Persistent Volume allocation.

**Comment by maciaszczykm** [comment]
Still, it would be confusing to attach metrics of all nodes to paginated response of only 10 nodes for example. If that needs to be done on the backend side then do it as a separate API endpoint.

**Comment by afbjorklund** [comment]
Hmm, I definitely want to show the entire cluster...

Like how we show the status for **all** the pods (in Workload Status), but then page through a few at a time in the details ?

**Comment by floreks** [comment]
Like @maciaszczykm mentioned, I'd also add a new endpoint like `api/v1/nodes/metrics` that would return cluster-wide metrics.

**Comment by afbjorklund** [comment]
Ok, I will split into two separate PRs - one for the status, one for the metrics

Will also open a separate issue about adding support for node ephemeral storage
